# Header
menu:
  Home: /
  Tags: tags/
  Categories: categories/
  Archives: archives/
  About: about/

# Content
excerpt_link: Read more >>
fancybox: true

# Sidebar
sidebar: 
widgets:
- category
- tag
# - tagcloud
- archive
- recent_posts
# - links

# Links
links:

# Miscellaneous
google_analytics:
favicon: /logo.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# scrollUp 样式
scrollUp: image
